#!/bin/csh -f
#
# This script calculated the Energy budget terms for POP model output.
# It can average multiple monthly average output files to create e.g. yearly averages.
# This script is adapted from the Atlantic salt budget time series script.
# 

# -----------------------------------
#  User can change parameters below
# -----------------------------------

set ntavg     = $argv[1]  # time average to be used; 1, 5, or 11 years
set year      = $argv[2]  # year
if ( "$ntavg" == 1 ) then
  set inputfile = "/projects/0/samoc/jan/Andree/t.t0.1_42l_nccs01.tavg.year.$year"
else if ( "$ntavg" == 5 ) then
  set inputfile = "/projects/0/samoc/jan/Andree/t.t0.1_42l_nccs01.tavg.5year.$year"
else if ( "$ntavg" == 11 ) then
  set inputfile = "/projects/0/samoc/jan/Andree/t.t0.1_42l_nccs01.tavg.11.year.$year"
else if ( "$ntavg" == 51 ) then
  set inputfile = "/projects/0/samoc/jan/Andree/t.t0.1_42l_nccs01.tavg.51.year.$year"
endif

ifort -O3 -convert big_endian -o LEC_$ntavg$year LEC.f90

# timeseries info
# (data for extravars-case only exists for 026903-027001 at the moment;
# the file that contains a certain month is written on the 1st day of the next month;
# so the month in inputfilename is always 1 month up front
# e.g. t.t0.1_42l_nccs01.012002 contains January year 120;
# this means data is available for 02-269 to 12-269)

# record numbers in tavg file
# (CAUTION: these vary between experiments)
# (the following values are for the run_henk_mixedbc_extravars case)

set nrec_UVEL          =    1
set nrec_VVEL          =   43
set nrec_UVEL2         =   85
set nrec_VVEL2         =  127
set nrec_STFRHO        =  169
set nrec_SSFRHO        =  170
set nrec_EVAPRHO       =  171
set nrec_PRECIPRHO     =  172
set nrec_SWRESTRHO     =  173
set nrec_SSRESTRHO     =  174
set nrec_RUNOFFRHO     =  175
set nrec_UTAUX         =  176
set nrec_VTAUY         =  177
set nrec_ALPHA01       =  178
set nrec_BETA01        =  179
set nrec_KE            =  180
set nrec_TEMP          =  222
set nrec_SALT          =  264
set nrec_RHO           =  306
set nrec_UV            =  348
set nrec_SSH           =  390
set nrec_SWNET         =  391
set nrec_LWNET         =  392
set nrec_LATENT        =  393
set nrec_SENSIBLE      =  394
set nrec_T_STRONG_REST =  395
set nrec_EVAP          =  396
set nrec_PRECIP        =  397
set nrec_S_WEAK_REST   =  398
set nrec_S_STRONG_REST =  399
set nrec_RUNOFF        =  400
set nrec_SHF           =  401
set nrec_SFWF          =  402
set nrec_TAUX          =  403
set nrec_TAUY          =  404
set nrec_WVEL          =  405
set nrec_UEU           =  447
set nrec_VNU           =  489
set nrec_UEV           =  531
set nrec_VNV           =  573
set nrec_WTU           =  615
set nrec_WTV           =  657
set nrec_UET           =  699
set nrec_VNT           =  741
set nrec_WTT           =  783
set nrec_UES           =  825
set nrec_VNS           =  867
set nrec_WTS           =  909
set nrec_ADVT          =  951
set nrec_ADVS          =  952
set nrec_Q             =  953
set nrec_PD            =  995
set nrec_PD2           = 1037
set nrec_RHO2          = 1079
set nrec_UW            = 1121
set nrec_VW            = 1163
set nrec_RHOU          = 1205
set nrec_RHOV          = 1247
set nrec_RHOW          = 1289
set nrec_URHO          = 1331
set nrec_VRHO          = 1373
set nrec_WRHO          = 1415
set nrec_PDW           = 1457
set nrec_PDU           = 1499
set nrec_PDV           = 1541
set nrec_UPD           = 1583
set nrec_VPD           = 1625
set nrec_WPD           = 1667

set nrec_UEU           =  447
set nrec_UEV           =  531
set nrec_VNU           =  489
set nrec_VNV           =  573
set nrec_WTU           =  615
set nrec_WTV           =  657

# START WITH THE CALCULATION OF THE ENERGY BUDGET
# The program needs the following inputs
# 1.  3600,2400,42 = dimension of grid
# 2.  name of GRID file
# 3.  name of KMT file
# 4.  name of in_depths file (contains thickness of depth levels)
# 5.  name of DZBC file
# 6.  name of tavg file
# 7.  year
# 8.  averaging period
# 9.  nrec field indices

echo "3600,2400,42" >> in_list_$ntavg$year
echo "/home/dijkbio/andre/LEC/input/grid.3600x2400.fob.da" >> in_list_$ntavg$year
echo "/home/dijkbio/andre/LEC/input/kmt_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black" >> in_list_$ntavg$year
echo "/home/dijkbio/andre/LEC/input/in_depths.42.dat" >> in_list_$ntavg$year
echo "/home/dijkbio/andre/LEC/input/dzbc_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black" >> in_list_$ntavg$year
echo "$inputfile" >> in_list_$ntavg$year
echo "$year" >> in_list_$ntavg$year
echo "$ntavg" >> in_list_$ntavg$year
echo "$nrec_UVEL, $nrec_VVEL, $nrec_UVEL2, $nrec_VVEL2, $nrec_STFRHO, $nrec_SSFRHO, $nrec_EVAPRHO, $nrec_PRECIPRHO, $nrec_SWRESTRHO, $nrec_SSRESTRHO, $nrec_RUNOFFRHO, $nrec_UTAUX, $nrec_VTAUY, $nrec_ALPHA01, $nrec_BETA01, $nrec_KE, $nrec_TEMP, $nrec_SALT, $nrec_RHO, $nrec_UV, $nrec_SSH, $nrec_SWNET, $nrec_LWNET, $nrec_LATENT, $nrec_SENSIBLE, $nrec_T_STRONG_REST, $nrec_EVAP, $nrec_PRECIP, $nrec_S_WEAK_REST, $nrec_S_STRONG_REST, $nrec_RUNOFF, $nrec_SHF, $nrec_SFWF, $nrec_TAUX, $nrec_TAUY, $nrec_WVEL, $nrec_UEU, $nrec_VNU, $nrec_UEV, $nrec_VNV, $nrec_WTU, $nrec_WTV, $nrec_UET, $nrec_VNT, $nrec_WTT, $nrec_UES, $nrec_VNS, $nrec_WTS, $nrec_ADVT, $nrec_ADVS, $nrec_Q, $nrec_PD, $nrec_PD2, $nrec_RHO2, $nrec_UW, $nrec_VW, $nrec_RHOU, $nrec_RHOV, $nrec_RHOW, $nrec_URHO, $nrec_VRHO, $nrec_WRHO, $nrec_PDW, $nrec_PDU, $nrec_PDV, $nrec_UPD, $nrec_VPD, $nrec_WPD, $nrec_UEU, $nrec_UEV, $nrec_VNU, $nrec_VNV, $nrec_WTU, $nrec_WTV" >> in_list_$ntavg$year

./LEC_$ntavg$year < in_list_$ntavg$year


rm LEC_$ntavg$year
rm in_list_$ntavg$year
 
echo "All calculations successfully done."

#mv LEC_bin_$ntavg$year /projects/0/samoc/jan/Andree/LEC_bin_$ntavg$year

# cp LEC.hdr /projects/0/samoc/jan/Andree/LEC_bin_$year.hdr 
# ./bin2nc/bin2nc /projects/0/samoc/jan/Andree/LEC_bin_$year rKm

# # creating 0.1 deg curvilinear netCDF files of LEC terms
# cp LEC_bin.hdr LEC_bin_$year.hdr
# ./bin2nc/bin2nc LEC_bin_$year rPm
# ./bin2nc/bin2nc LEC_bin_$year rPe
# ./bin2nc/bin2nc LEC_bin_$year rKm
# ./bin2nc/bin2nc LEC_bin_$year rKe
# rm LEC_bin_$year.hdr 

# # creating interpolated recangular 0.4 deg netCDF from binary

# ./tx0.1_to_0.4/nccurv2ncrect.sc LEC_bin_$year .
# mv LEC_bin_$year.interp900x602.nc /projects/0/samoc/jan/Andree/LEC_interp900x602_$year.nc
# rm LEC_bin_$year.hdr
# rm LEC_bin_$year




