#!/bin/csh -f
#
# This script compiles analyze analyze_LEC.f90 which calculates LEC quantities .
# 

set ntavg     = $argv[1]
set year      = $argv[2]
set inputfile = "/projects/0/samoc/jan/Andree/LEC_bin_$ntavg"_"$year"

ifort -O3 -convert big_endian -o analyze_LEC_$year analyze_LEC.f90 -lnetcdf -lnetcdff

# record numbers in tavg file

set nrec_rPm  =    1
set nrec_rPe  =   43
set nrec_rKm  =   85
set nrec_rKe  =  127
set nrec_gPm  =  169
set nrec_gPe  =  170
set nrec_gKm  =  171
set nrec_gKe  =  172
set nrec_gPmh =  173
set nrec_gPms =  174
set nrec_gPeh =  175
set nrec_gPes =  176
set nrec_cPem =  177
set nrec_cKem =  219
set nrec_cPKm =  261
set nrec_cPKe =  303
set nrec_TEMP =  345


# The program needs 7 inputs
# 1.  3600,2400,42 = dimension of grid
# 2.  name of GRID file
# 3.  name of KMT file
# 4.  name of in_depths file (contains thickness of depth levels)
# 5.  name of DZBC file
# 6.  name of tavg file
# 7.  year
# 8.  running mean length ntavg
# 9.  nrec field indices

echo "3600,2400,42" >> in_list_$year
echo "/home/dijkbio/andre/LEC/input/grid.3600x2400.fob.da" >> in_list_$year
echo "/home/dijkbio/andre/LEC/input/kmt_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black" >> in_list_$year
echo "/home/dijkbio/andre/LEC/input/in_depths.42.dat" >> in_list_$year
echo "/home/dijkbio/andre/LEC/input/dzbc_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black" >> in_list_$year
echo "$inputfile" >> in_list_$year
echo "$year" >> in_list_$year
echo "$ntavg" >> in_list_$year
echo "$nrec_rPm, $nrec_rPe, $nrec_rKm, $nrec_rKe, $nrec_gPm, $nrec_gPe, $nrec_gKm, $nrec_gKe, $nrec_gPmh, $nrec_gPms, $nrec_gPeh, $nrec_gPes, $nrec_cPem, $nrec_cKem, $nrec_cPKm, $nrec_cPKe, $nrec_TEMP" >> in_list_$year

./analyze_LEC_$year < in_list_$year


rm analyze_LEC_$year
rm in_list_$year
 
echo "All calculations successfully done."
