#!/bin/csh -f
#
# This script calculated the Energy budget terms for POP model output.
# It can average multiple monthly average output files to create e.g. yearly averages.
# This script is adapted from the Atlantic salt budget time series script.
# 

# -----------------------------------
#  User can change parameters below
# -----------------------------------

set case = $argv[1]
echo "case: " $case
# POP control run
if ( $case == 1 ) then
   set inputfile  = "/projects/0/samoc/jan/Andree/t.t0.1_42l_nccs01.tavg.year."
   set outputfile = "output/BSF_POP_bin.out"
   set kmtfile    = "/home/dijkbio/andre/LEC/input/kmt_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black"
   set dzbcfile   = "/home/dijkbio/andre/LEC/input/dzbc_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black"
   set first_yr   =  76
   set last_yr    = 326

# POP DP closed run
else if ( $case == 2 ) then
   set inputfile  = "/projects/0/samoc/jan/Andree/t.t0.1_42l_nccs01.dpc.tavg.year."
   set outputfile = "output/BSF_POP_bin_dp.out"
   set kmtfile    = "/home/dijkbio/andre/LEC/input/kmt_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black_CLOSED_DRAKE_PASSAGE"
   set dzbcfile   = "/home/dijkbio/andre/LEC/input/dzbc_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black_CLOSED_DRAKE_PASSAGE"
   set first_yr   =  75
   set last_yr    = 296

# eSALSA ev run
else if ( $case == 3 ) then
   set inputfile  = "/projects/0/samoc/jan/Andree/"
   set outputfile = "output/BSF_eSALSA_bin.out"
   set kmtfile    = "/home/dijkbio/andre/LEC/input/kmt_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black"
   set dzbcfile   = "/home/dijkbio/andre/LEC/input/dzbc_pbc.p1_tripole.s2.0-og.20060315.no_caspian_or_black"
   set first_yr   = 216
   set last_yr    = 226

endif

ifort -O3 -convert big_endian -o BSF_$case ../f90/BSF.f90

# timeseries info
# (data for extravars-case only exists for 026903-027001 at the moment;
# the file that contains a certain month is written on the 1st day of the next month;
# so the month in inputfilename is always 1 month up front
# e.g. t.t0.1_42l_nccs01.012002 contains January year 120;
# this means data is available for 02-269 to 12-269)

# record numbers in tavg file
# (CAUTION: these vary between experiments)
# (the following values are for the run_henk_mixedbc_extravars case)

set nrec_UVEL     =    1

# START WITH THE CALCULATION OF THE ENERGY BUDGET
# The program needs 7 inputs
# 1.  3600,2400,42 = dimension of grid
# 2.  name of GRID file
# 3.  name of KMT file
# 4.  name of in_depths file (contains thickness of depth levels)
# 5.  name of DZBC file
# 6.  name of tavg file
# 7.  nrec field indices

set t = $first_yr
while ( $t <= $last_yr )
  echo "$inputfile$t"
  echo "3600,2400,42" >> in_list_$case
  echo "/home/dijkbio/andre/LEC/input/grid.3600x2400.fob.da" >> in_list_$case
  echo "$kmtfile" >> in_list_$case
  echo "/home/dijkbio/andre/LEC/input/in_depths.42.dat" >> in_list_$case
  echo "$dzbcfile" >> in_list_$case
  echo "$inputfile$t" >> in_list_$case
  echo "$t"      >> in_list_$case
  echo "$nrec_UVEL" >> in_list_$case
  echo "$outputfile" >> in_list_$case
  if ( -f $inputfile$t ) then
    ./BSF_$case < in_list_$case
  endif
  rm in_list_$case
  @ t++
end 
rm BSF_$case
echo "All calculations successfully done."
