#!/bin/csh -f
#
ifort -O3 -convert big_endian -o geometry_program ../f90/geometry.f90 ../f90/sub_model.f90 ../f90/sub_physics.f90
./geometry_program
rm geometry_program
echo "All calculations successfully done."
